import { chromium, devices } from "playwright";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices["iPhone 13"], viewport: { width: 390, height: 844 } });
const page = await ctx.newPage();
await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
await sleep(2500);
await page.setViewportSize({ width: 1280, height: 844 });
await sleep(400);
await page.click('button[aria-label="Export canvas as PNG"]');
const li = page.locator('li[data-swipe-direction][data-state="open"]').first();
await li.waitFor({ state: "visible", timeout: 25000 });
await page.setViewportSize({ width: 390, height: 844 });
await sleep(600);
const box = await li.boundingBox();
const cx = box.x + box.width / 2, cy = box.y + box.height / 2;
await page.mouse.move(cx, cy);
await page.mouse.down();
await page.mouse.move(cx, cy - 55, { steps: 6 });
await sleep(120);
await page.screenshot({ path: "download/t174-toast-mid-drag.png" });
await page.mouse.up();
await browser.close();
console.log("shot saved");
