// t241 sanity — the run-report echo's dialect, checked BEFORE any wire
// (lamps before wires, t237's law): a synthetic dossier carrying EVERY
// construct the profile builder can emit, plus the traps.
import { buildProfileReportHtml } from "../src/lib/report-html.ts";

const IMG =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";

const md = [
  "# CryoFlow run report — QA Refine3D",
  "",
  "| Field | Value |",
  "| --- | --- |",
  "| Job type | `relion_refine` |",
  "| Duration | 12m 30s |",
  "",
  "**Contents**",
  "",
  '<a id="contents" name="contents"></a>',
  "1. [Summary](#summary)",
  "2. [FSC curve](#fsc-curve)",
  "3. [Outputs on disk](#outputs-on-disk)",
  "",
  '<a id="summary" name="summary"></a>',
  "## Summary",
  "",
  "Refined to **9.44 Å** — FSC 0.143 at 9.44 Å.",
  "",
  '<a id="fsc-curve" name="fsc-curve"></a>',
  "## FSC curve",
  "",
  "| Shell | FSC |",
  "| ---: | ---: |",
  "| 0.10 | 0.98 |",
  "| 0.20 | 0.71 |",
  "",
  `![FSC curve for QA Refine3D](${IMG})`,
  "",
  "- FSC 0.143 resolution: **9.44 Å**",
  "- FSC 0.5 (half-bit) resolution: **7.08 Å**",
  "",
  '<a id="outputs-on-disk" name="outputs-on-disk"></a>',
  "## Outputs on disk",
  "",
  "- 1 map/image file — latest: `postprocess.mrc`",
  "",
  "_Generated by CryoFlow on 2026-09-16T03:00:00.000Z_",
  "",
  "---",
  "",
  "[↑ Back to contents](#contents)",
  "",
].join("\n");

const html = buildProfileReportHtml(md);
const traps = [];
const ok = (cond, name) => {
  if (!cond) traps.push(name);
};

ok(html.startsWith("<!DOCTYPE html>"), "doctype first");
ok(!/<script/i.test(html), "zero script");
ok(!/<link|@import|src="http/i.test(html), "zero external refs");
ok(/<a id="summary">Summary<\/a>|<h2 id="summary">/.test(html), "section anchor folded into heading id");
ok((html.match(/<h2 id="/g) || []).length === 3, "all three section anchors folded");
ok(html.includes('<a id="contents" name="contents"></a>'), "contents anchor emitted verbatim");
ok((html.match(/<a href="#[a-z0-9-]+">/g) || []).length === 4, "four real links (3 contents + back)");
ok(!/\[Summary\]/.test(html), "no raw md link syntax left");
ok(html.includes(`<img src="${IMG}"`), "data-URI image carried");
ok((html.match(/<figure class="shot">/g) || []).length === 1, "one figure");
ok((html.match(/<hr>/g) || []).length === 1, "one hr");
ok((html.match(/<ol>/g) || []).length === 1, "one ordered list");
ok(html.includes("<title>CryoFlow run report — QA Refine3D</title>"), "title from h1");
ok(html.includes("<strong>9.44 Å</strong>"), "bold survives");
ok(html.includes("<em>Generated by CryoFlow on 2026-09-16T03:00:00.000Z</em>"), "provenance line survives");
ok(html.includes("<code>relion_refine</code>"), "code in cell survives");
ok(html.includes('<td class="r">0.98</td>'), "right-aligned cell class");
ok(html.includes("h2:target, h3:target { animation: echo-glow"), "landing light rides the shared CSS");
ok(!html.includes("![FSC"), "no raw image syntax left");

// determinism relative to input (the md's own clock line is the md's business)
const html2 = buildProfileReportHtml(md);
ok(html === html2, "same md -> same bytes");

// the http-image trap: a non-data image src must fall through as TEXT
const hostile = "# T\n\n![x](https://evil.example/pic.png)\n";
const hostileOut = buildProfileReportHtml(hostile);
ok(!hostileOut.includes("<img"), "http image NOT rendered as a picture");
ok(hostileOut.includes("&lt;img") || hostileOut.includes("https://evil"), "hostile line falls through as text");

// the http-link trap: only #-anchors become links
const hostile2 = "See [the docs](https://example.com) and [inside](#summary).";
const hostile2Out = buildProfileReportHtml(hostile2);
ok(!hostile2Out.includes('href="https://example.com"'), "http link NOT a link");
ok(hostile2Out.includes('href="#summary"'), "#-link still a link");

if (traps.length) {
  console.error("SANITY FAIL:\n  - " + traps.join("\n  - "));
  process.exit(1);
}
console.log("T241 SANITY GREEN — dialect complete, traps hold, deterministic");
